# file: tasks/main.yml

- name: ERLPMD | checkout erlpmd from github into /tmp/erlpmd
  git: repo={{ repo_url }}
       version={{ repo_version}}
       dest={{ tmp }}
  register: erlpmd_downloaded

- name: ERLPMD | build erlpmd in /tmp/erlpmd
  command: make chdir={{ tmp }}

- name: ERLPMD | make install_dir - /usr/lib/erlang/lib/erlpmd-version
  file: path={{ install_dir }}
        state=directory
        owner={{ ansible_ssh_user }}
        mode=0755

- name: ERLPMD | copy erlpmd ebin to install dir
  command: cp -r {{ tmp }}/ebin {{ install_dir }}/

- name: ERLPMD | copy erlpmd priv
  command: cp -r {{ tmp }}/priv {{ install_dir }}/
